### ISSUE TITLE
Cisco EOX API: Update failed: time data '' does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by Vladimir-Ilyin** [hoelsner/product-database#7]
Hello!

When I start manual query for update EOX data receive an error:
**Update failed: time data '' does not match format '%Y-%m-%d'**

EOX data not updated, what need to change to restore EOX update?

**Comment by hoelsner** [comment]
Hi,

can you please provide the query that produces the error? The API contains sometimes invalid entries within the date field. Furthermore, I removed the manual query feature some time ago and replaced it with a manual trigger for the synchronization with the Cisco EoX API. For this reason, I recommend to update to the latest version (master branch). 

Kind regards,
Henry

**Comment by hoelsner** [comment]
Hello, 
after a closer look I found the issue. The Cisco EoX API now provides always an `EndOfSecurityVulSupportDate` without a valid value. For this reason the parser throws an error, but only for the `end_of_sec_vuln_supp_date` value. The other date values are updated in the database. I'll fix this with the next version. 
Greetings, Henry

**Comment by Vladimir-Ilyin** [comment]
Hello!

For the query NAM2204* I get the following:

```
Query: NAM2204*
[
    {
        "PID": "NAM2204-SFP",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-RAILS=",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-RJ45",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-BRKTS=",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    }
]
```

new records are not created

**Comment by hoelsner** [comment]
Hi @Vladimir-Ilyin,

your're right. I fixed the issue right now. Please update to [v0.9](https://github.com/hoelsner/product-database/releases/tag/v0.9) and then it should work again. Please note, that I added a password to the internal redis connection. Add the `PDB_REDIS_PASSWORD` configuration option to your env file.

Let me know if this works for you. 

Best regards,
Henry

**Comment by Vladimir-Ilyin** [comment]
Hello Henry!

  I update tool to latest release (1faed63), but problem persist

  For query "NAM2204*" i receive following error:

```
Query: NAM2204*
[
    {
        "PID": "NAM2204-SFP",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-RAILS=",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-RJ45",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    },
    {
        "PID": "NAM2204-BRKTS=",
        "blacklist": false,
        "created": true,
        "message": "Update failed: time data '' does not match format '%Y-%m-%d'",
        "updated": true
    }
]
```

**Comment by hoelsner** [comment]
Hi @Vladimir-Ilyin,

have you rebuild the container after the git pull with the following command?

```
docker-compose build
```

You need to recreate the containers with `docker-compose up -d`. Please note that the manual synchronization is not available anymore in the current version. You can configure the the periodic sync at "Admin" > "Settings" at the tab "Cisco API settings". The synchronization can be trigged at "Admin" > "Status" with the button "Start synchronization with Cisco EoX API now". 

Best regards, 
Henry

**Comment by Vladimir-Ilyin** [comment]
Hello Henry!

I do not use the docker, I use a standalone server with installed from github copy and sync it with the repository

Using the mechanism of periodic synchronization, I also get errors and data is not updated and new records do not appear

```
Synchronize local database with Cisco EoX API

Query: NAM2204*
The following products are affected by this update:

    create the Product NAM2204-SFP in the database (Update failed: time data '' does not match format '%Y-%m-%d')
    create the Product NAM2204-RAILS= in the database (Update failed: time data '' does not match format '%Y-%m-%d')
    create the Product NAM2204-RJ45 in the database (Update failed: time data '' does not match format '%Y-%m-%d')
    create the Product NAM2204-BRKTS= in the database (Update failed: time data '' does not match format '%Y-%m-%d')
```

Best regards,
Vladimir

**Comment by hoelsner** [comment]
Hello @Vladimir-Ilyin,

I removed the standalone server deployment from the repository some time ago, because Docker is easier (and more reliable) to setup and maintain. Can you please setup a Docker Engine on your Server and use the docker-compose file? You find the instructions how to setup Docker on a Linux Server [here (official Docker documentation)](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce).

After the installation of Docker on the server, you need to run the following commands to setup the Product Database:

```bash
cp env.prod_template env.myinstance
# it is recommended to change the default values within the env.myinstance (plschgme values)
export COMPOSE_PROJECT_NAME=productdb
export INSTANCE_CONFIG=myinstance
docker-compose build
docker-compose up -d
``` 

Best regards, 
Henry
